**Assignment 4 CC By Jatin Jindal(102316061)**

Ques 1.Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
1. Addition of 2 in all the element
2. Multiply 3 with all the elements
3. Divide every element by 2

In [ ]:
import numpy as np

# Create a 1D array with 5 elements
arr = np.array([1, 2, 3, 4, 5])

# a) Add 2 to all the elements
arr_add = arr + 2

# b) Multiply 3 with all the elements
arr_mul = arr * 3

# c) Divide every element by 2
arr_div = arr / 2

# Output the results
print("Original Array:", arr)
print("After adding 2:", arr_add)
print("After multiplying by 3:", arr_mul)
print("After dividing by 2:", arr_div)


Original Array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


Ques 2.Questions on Basic NumPy Array: <br>
a. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) <br>
b. Find the most frequent value and their indice(s) in the following arrays: <br>
    i. x = np.array([1,2,3,4,5,1,2,1,1,1])  <br>
    ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np
from scipy import stats

# Part (a): Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])

# Reverse the array
arr_reversed = arr[::-1]

# Part (b): Find the most frequent value and their indices in the arrays
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

# i. For array x
mode_x = stats.mode(x)  # This returns a ModeResult object
# Check if mode_x.mode is a scalar (directly use it if it is)
indices_x = np.where(x == mode_x.mode)[0]

# ii. For array y
mode_y = stats.mode(y)  # This returns a ModeResult object
# Check if mode_y.mode is a scalar (directly use it if it is)
indices_y = np.where(y == mode_y.mode)[0]

# Output the results
print("Reversed Array:", arr_reversed)
print(f"Most frequent value in x: {mode_x.mode} at indices: {indices_x}")
print(f"Most frequent value in y: {mode_y.mode} at indices: {indices_y}")


Reversed Array: [5 4 6 3 2 1]
Most frequent value in x: 1 at indices: [0 5 7 8 9]
Most frequent value in y: 1 at indices: [0 1 2]


Ques 3.For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
1. Access 1st row, 2nd column
2. Access 3rd row, 1st column

In [ ]:
# 2D Array
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Access 1st row, 2nd column
element_1 = arr_2d[0, 1]

# b) Access 3rd row, 1st column
element_2 = arr_2d[2, 0]

print("1st row, 2nd column:", element_1)
print("3rd row, 1st column:", element_2)


1st row, 2nd column: 20
3rd row, 1st column: 70


Ques4. Write program to create an 1-D NumPy array named _Your Name_ with evenly
spaced 25 numbers from 10 to 100 using linspace().
- Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed
by the array.
- Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
# Create an array with 25 numbers from 10 to 100
arr_name = np.linspace(10, 100, 25)

# Print properties
print("Array:", arr_name)
print("Dimensions:", arr_name.ndim)
print("Shape:", arr_name.shape)
print("Total Elements:", arr_name.size)
print("Data Type:", arr_name.dtype)
print("Total Bytes:", arr_name.nbytes)

# Transpose using reshape()
arr_transpose = arr_name.reshape(25, 1)

# Using T attribute for transpose
arr_transpose_t = arr_name.T

print("Transpose using reshape():", arr_transpose)
print("Transpose using T attribute:", arr_transpose_t)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200
Transpose using reshape(): [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Ques 5. Create a 2-D Array of three rows and four columns, named _ucs420<< yourname >>_ with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. <br>Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped _ucs420<< your_name >>_. Resize the array to two rows and three
columns and name it as resized _ucs420<< your_name >>_.

In [ ]:
import numpy as np

# Create a 2-D array named _ucs420_jatin with 3 rows and 4 columns
ucs420_jatin = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])

# Compute the mean, median, max, min, unique elements
mean_val = np.mean(ucs420_jatin)
median_val = np.median(ucs420_jatin)
max_val = np.max(ucs420_jatin)
min_val = np.min(ucs420_jatin)
unique_elements = np.unique(ucs420_jatin)

# Reshape the array to 4 rows and 3 columns
reshaped_ucs420_jatin = ucs420_jatin.reshape(4, 3)

# Resize the array to 2 rows and 3 columns using np.resize() (this returns a new array)
resized_ucs420_jatin = np.resize(ucs420_jatin, (2, 3))

# Print results
print("Original Array (ucs420_jatin):\n", ucs420_jatin)
print("\nMean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique Elements:", unique_elements)

print("\nReshaped Array (4 rows, 3 columns):\n", reshaped_ucs420_jatin)
print("\nResized Array (2 rows, 3 columns):\n", resized_ucs420_jatin)


Original Array (ucs420_jatin):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 rows, 3 columns):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2 rows, 3 columns):
 [[10 20 30]
 [40 50 60]]
